### ISSUE TITLE
Climber.retract() potentially leaves robot in bad state

### ISSUE THREAD

**Issue by DigitalZilla** [Team3309/FRC2021-Offseason#11]
https://github.com/Team3309/FRC2021-Offseason/blob/894248e37c6267369d2eabc82c6ecf11a0ed7a7b/src/main/java/frc/robot/subsystems/ClimberSubsystem.java#L42

deploy() sets hasBeenExtended to true. retract() does not set this back to false. By the name of the variable, (_has..._ instead of _is..._), that would seem correct. However, this variable is used to block, activateWinch(). If the winch can only be activated **when** the climber is extended, than this variable should probably be changed to isExtended, and set to false on retract()

**Comment by MarkGhebrial** [comment]
The thing is, the winch needs to activate when the the pistons are retracted.

Climbing sequence:
 1. Climber extends
 2. Robot drives into bar, latching the hooks onto it
 3. Pistons retract, but do not return to the climber to its stowed state because of the hooks
 4. Winch activates (_while the pistons are retracted!_)

The winch cannot act in reverse because of the ratchet, so we don't want it to activate if the operators accidentally press the button that turns it on. To mitigate that, hasBeenExtended is supposed to stop the winch from activating until the operators have initiated the endgame sequence by extending the climber.
